services:
  - type: web
    name: doctor4you-backend
    runtime: docker
    dockerfilePath: health_tracker/Dockerfile
    dockerContext: health_tracker
    plan: free
    envVars:
      - key: PORT
        value: "8000"
